export enum OrderStatus {
  CREATED = 'CREATED',
  ADDRESS_ASSIGNED = 'ADDRESS_ASSIGNED',
  PENDING_INCOMING = 'PENDING_INCOMING',
  COMPLETE_CONFIRMED = 'COMPLETE_CONFIRMED',
  FORWARDED = 'FORWARDED',
  SETTLED = 'SETTLED',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  REFUND_PENDING = 'REFUND_PENDING',
  REFUNDED = 'REFUNDED',
  OVERPAID = 'OVERPAID'
}

export enum RefundStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED'
}

export enum PayoutStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED'
}
